### ISSUE TITLE
motion sensor

### ISSUE THREAD

**Issue by sangkooki** [jchristman/homebridge-timer#1]
Hi,

Thank you for your plugin.

I use 'button pressed' and 'button released' instead of motion sensors.

I want boolean option to have motion sensor or not to have motion sensor.

**Comment by jchristman** [comment]
Interesting concept. Now that I think of it, the switch I use to toggle the timer could be used in the same way. I'm planning on rewriting with targeting homebridge's API 2.0 here pretty soon, so I'll make an option to include motions sensors, a push button, or just the switch itself.

**Comment by sangkooki** [comment]
Great news.

Thanks.

**Comment by jchristman** [comment]
This plugin's functionality is included in iOS 11. I will no longer be supporting this package.
